name: Validate Markdown Structure

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  validate-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Markdown validator
        run: python .github/scripts/validate_structure.py
